### ISSUE TITLE
Py4JException: Error while obtaining a new communication channel after registering listener

### ISSUE THREAD

**Issue by brysd** [sashgorokhov/pyspark-spy#2]
Hi Alexander, I stumbled on this repo when looking for solutions to include a spark listener in pyspark.
Nice work.

However, I couldn't get it to work and then tried with this repo and ran the tests.
Whatever I do it blocks on communication for the listeners;

ERROR AsyncEventQueue: Listener Proxy33 threw an exception
py4j.Py4JException: Error while obtaining a new communication channel
	at py4j.CallbackClient.getConnectionLock(CallbackClient.java:257)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:377)
	at py4j.CallbackClient.sendCommand(CallbackClient.java:356)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:106)
	at com.sun.proxy.$Proxy33.onJobStart(Unknown Source)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:37)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1471)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/java.net.Socket.connect(Socket.java:558)
	at java.base/java.net.Socket.<init>(Socket.java:454)
	at java.base/java.net.Socket.<init>(Socket.java:264)
	at java.base/javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:277)
	at py4j.PythonClient.startClientSocket(PythonClient.java:192)
	at py4j.PythonClient.getConnection(PythonClient.java:213)
	at py4j.CallbackClient.getConnectionLock(CallbackClient.java:250)

Starting a spark session and context is not the issue, tried that separately but from the moment on the listener is being registered, the communication error occurs. I know it's been a while, but do you have any idea what could be going on? It could be on the spark side or on the py4j side. Any pointers would be great. I'm happy to investigate and test this further.

**Comment by brysd** [comment]
After some more investigation, we found out that it works on a bare metal machine and on WSL2. However it doesn't seem to work in a docker container. It's not yet clear why and whether we would need to set PYSPARK_GATEWAY_PORT and PYSPARK_GATEWAY_SECRET or not. Current tests demonstrate that we are not able to run pyspark-spy in our docker environment which exposes only 2 ports (port 22-ssh and port 5000-flask)
